config/routes.rb
ListApp::Application.routes.draw do
  resources :password_resets

  match "signup/", to: 'users#new'

  match 'team/', to: 'static_pages#team'
  match 'about/', to: 'static_pages#about'
  match 'home/', to: 'static_pages#home'

  match 'contribute/', to: 'static_pages#contribute'
  match 'sync/', to: 'sync#show'
  match 'get_sync/', to: 'sync#get_sync'

  match '/auth/facebook/callback', to: 'sessions#facebook'
  match '/auth/failure', to: redirect('/')
  root :to => 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
      get :fb_friends
      post :invite_by_email
    end
    collection do
      get :syncable_users
    end
  end

  resources :relationships, only: [:destroy, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :lists, :only => [:create, :destroy, :new, :show] do
    member do
      post :add_to
    end
  end
  resources :list_items, :only => [:create, :destroy]
  resources :restaurants, :only => [:new, :create, :show, :edit] do
    member do
      post :add_to_list
      post :post_to_facebook
      resources :comments, :only => [:create, :destroy]
    end
    collection do
      get :search
    end
  end

  resources :edit_requests, only: [:index, :create, :show] do
    member do
      post :accept
      post :reject
    end
  end
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete #this means it will be invoked using the DELETE request

  match '/search', to: 'search#search'

end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id         :integer         not null, primary key
#  user_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  city_id    :integer
#

class List < ActiveRecord::Base
  acts_as_story
  attr_accessible :user_id, :city_id

  belongs_to :user
  belongs_to :city
  has_many :list_items, dependent: :destroy
  has_many :restaurants, through: :list_items

  validates :user_id, :city_id, :presence => true
  validates_uniqueness_of :city_id, scope: :user_id

  MAX_ITEMS_PER_LIST = 30

  def list_item_for(restaurant)
    list_items.find_or_create_by_restaurant_id(restaurant.id)
  end


  def fb_share_title
    "#{user.full_name}'s Bitelist"
  end

  def fb_share_caption
    "Places you love to eat at."
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :signed_in_user, :only => [:new, :create, :destroy]
  before_filter :correct_user, :only => :destroy

  #GET request for displaying how to create a new List
  def new
    @list = List.new
    @sfo = City.find_by_name 'San Francisco'
    @bos = City.find_by_name 'Boston'
    @hon = City.find_by_name 'Honolulu'
    @nyc = City.find_by_name 'New York'

    #TO DO: Need to add other cities => New York, Chicago, Hawaii, Los Angeles
  end

  #POST request for creating a new List
  def create
    @list = current_user.lists.find_by_city_id(list_params[:city_id])
    redirect_to @list and return if @list

    @list = current_user.lists.create(list_params)
    if @list.save
      flash[:success] = "Bitelist created for #{@list.city.name}! Start adding some restaurants below :)"
      # on success, redirect to newly created list
      redirect_to @list
    else
      flash[:error] = "Can't create more than one Bitelist for each city."
      # on failure, likely due to having a similar list; render new again
      render 'new'
    end
  end

  #DELETE request for killing a list => located on the user/:id page for showing a user
  def destroy
    @list.destroy
    redirect_to :back
  end

  #GET request to show lists/:id
  def show
    # if the list exists then store a class variable for the list to catch on the view

    @list = List.find_by_id(params[:id])
    if @list
      @restaurants = @list.restaurants

      # get the json for the maps
      @maps_json = @restaurants.to_gmaps4rails

      # pass in a variable to create a new List Item if the user enters a name into the text_field
      @list_item = ListItem.new
    else
      # else if there is no list, then redirect to root
      flash[:error] = "There was a problem finding your list."
      redirect_to new_session_path
    end
  end

  # handle the post from list
  def add_to
    list = current_user.lists.find(params[:restaurant][:list_id])
    count = list.list_items.count
    fb_ids = params[:restaurant][:name].split(',')

    #{[fb_id => nil], [fb_id2 => nil]}
    fb_restaurants = Hash[fb_ids.zip([])]

    list_restaurants = {}

    #all the restaurants in the list's city where it currently exists in the database with a facebook id and set the restaurant as the value
    list.city.restaurants.where(:fb_place_id => fb_ids).each do |restaurant|
      fb_restaurants[restaurant.fb_place_id] = restaurant
    end

    list.restaurants.each do |restaurant|
      list_restaurants[restaurant.id] = restaurant
    end

    fb_restaurants.each do |fb_id, restaurant|
      # if the resto doesn't exist then add it to the database
      if restaurant.nil?
        restaurant = Restaurant.create_from_facebook(fb_id, list.city_id)
      elsif list_restaurants[restaurant.id].present?
        next
      end

      #if there are too many restos then don't let user add anymore
      if count >= List::MAX_ITEMS_PER_LIST
        flash[:error] = "You can only have #{List::MAX_ITEMS_PER_LIST} restaurants per list!"
        break
      end
      list.list_items.create!(:restaurant_id => restaurant.id)
      count += 1
    end

    redirect_to :back
  end

  private

  def correct_user
    @list = current_user.lists.find_by_id(params[:id])
    redirect_to new_session_path if @list.nil?
  end

  def list_params
    @list_params ||= params[:list].slice(:city_id)
  end
end

app/helpers/lists_helper.rb
module ListsHelper
  def fb_share_link
    current_link = request.host_with_port + request.fullpath
    fb_params = {
      app_id:       ENV['FB_KEY'],
      link:         current_link,
      name:         @list.fb_share_title,
      caption:      @list.fb_share_caption,
      redirect_uri: "http://#{current_link}",
    }.map{|key, value| "#{key}=#{value}"}.join('&')
    "https://www.facebook.com/dialog/feed?#{fb_params}"
  end
end

app/views/lists/_list.html.haml
- @lists.each do |list|
  .ticket-outer
    .ticket-inner
      %h3.pull-left
        = link_to list.city.name_with_state, list
      - if current_user?(list.user)
        = link_to 'x', list, method: :delete, confirm: "Are you sure you want to delete this List?", style: "font-size: 20px; font-style:bold; margin-top:-3px;", class: 'close'
  %br/

app/views/lists/new.html.haml
- provide(:title, 'Create Bitelist')

%h1.big_title
  Create Bitelist

.row
  .span6.offset3
    = render 'shared/error_messages', :record => @list
.row
  .span4.offset2
    = form_for @list do |f|
      = image_submit_tag 'sf.jpg', :class => 'full_width'
      = f.hidden_field :city_id, :value => @sfo.id

  .span4
    = form_for @list do |f|
      = image_submit_tag 'boston.jpg', :class => 'full_width'
      = f.hidden_field :city_id, :value => @bos.id

  .span4.offset2
    = form_for @list do |f|
      = image_submit_tag 'hawaii.jpg', :class => 'full_width'
      = f.hidden_field :city_id, :value => @hon.id

  .span4
    = form_for @list do |f|
      = image_submit_tag 'nyc.jpg', :class => 'full_width'
      = f.hidden_field :city_id, :value => @nyc.id

app/views/lists/show.html.haml
- provide(:title, 'Bitelist')

%h1.big_title
  #{@list.user.first_name}'s #{@list.city.abbreviation} Bitelist

- # create a form to post to list_item_path (create method in list_items_controller)
.row{style: 'text-align:center;'}
  .span6.offset3
    - # only allow to post when it's the current user's account
    - if current_user? @list.user
      = form_for :restaurant, as: :post, :url => add_to_list_path(@list) do |f|
        = f.text_field :name, :id => 'search-restaurant'
        = f.hidden_field :list_id, value: @list.id
        = f.submit "Add to List", class: 'btn btn-primary', :style => 'margin-top:-2px; margin-bottom:0px;'
        = link_to fb_share_link, class: 'btn btn-info', :style => 'margin-left:10px; margin-top:10px; margin-bottom:0px;' do
          %i.icon-share.icon-white
          Share

.row
  .span6.offset3
    - if @list.list_items.count > 1
      = gmaps4rails(@maps_json)
    - elsif @list.list_items.count == 1
      = gmaps("map_options" => { "zoom" => 15, "auto_zoom" => false }, "markers" => { "data" => @maps_json })
    - else
      .ticket-outer
        .ticket-inner{style:'text-align:center;'}
          Nothing currently in #{@list.user.full_name}'s #{@list.city.abbreviation} Bitelist :(

- # list all the items in the list
.row
  .span6.offset3
    %ol.lists
      - @list.list_items.each do |item|
        .ticket-outer
          .ticket-inner
            .pull-left.list-image
              = image_tag item.restaurant.picture_url, size: '40x40'

            - if item.restaurant.name.length < 20
              = link_to item.restaurant.name, item.restaurant, class: 'pull-left list-item-text'
            - else
              = link_to truncate(item.restaurant.name.to_s, length: 20), item.restaurant, class: 'pull-left list-item-text'
            - if current_user? @list.user
              = link_to 'x', item, method: :delete, confirm: "Are you sure you want to delete this restaurant?", style: "font-size: 20px; font-style:bold; margin-top:-3px;", class: 'close'
        %br/

:javascript
  var options = {
    propertyToSearch: "name",
    hintText: "Enter a restaurant name in #{@list.city.name}",
    theme: "facebook",
    searchingText: "Searching Bitelist...",
    resultsFormatter: function(item){return "<li><img style='float:left; height:25px; width:25px; padding-right:10px;' src=" + item.url + "></img><div><b>" + item.name + "</b></div><div>" + item.address + " " + item.city + "</div></li>"},
  };
  $(document).ready(function () {
    $("#search-restaurant").tokenInput("/restaurants/search?city_id=#{@list.city.id}", options);
  });