config/routes.rb
ListApp::Application.routes.draw do
  resources :password_resets

  match "signup/", to: 'users#new'

  match 'team/', to: 'static_pages#team'
  match 'about/', to: 'static_pages#about'
  match 'home/', to: 'static_pages#home'

  match 'contribute/', to: 'static_pages#contribute'
  match 'sync/', to: 'sync#show'
  match 'get_sync/', to: 'sync#get_sync'

  match '/auth/facebook/callback', to: 'sessions#facebook'
  match '/auth/failure', to: redirect('/')
  root :to => 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
      get :fb_friends
      post :invite_by_email
    end
    collection do
      get :syncable_users
    end
  end

  resources :relationships, only: [:destroy, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :lists, :only => [:create, :destroy, :new, :show] do
    member do
      post :add_to
    end
  end
  resources :list_items, :only => [:create, :destroy]
  resources :restaurants, :only => [:new, :create, :show, :edit] do
    member do
      post :add_to_list
      post :post_to_facebook
      resources :comments, :only => [:create, :destroy]
    end
    collection do
      get :search
    end
  end

  resources :edit_requests, only: [:index, :create, :show] do
    member do
      post :accept
      post :reject
    end
  end
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete #this means it will be invoked using the DELETE request

  match '/search', to: 'search#search'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  first_name             :string(255)
#  last_name              :string(255)
#  email                  :string(255)
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#  password_digest        :string(255)
#  remember_token         :string(255)
#  admin                  :boolean         default(FALSE)
#  password_reset_token   :string(255)
#  password_reset_sent_at :datetime
#  fb_id                  :string(255)
#  provider               :string(255)
#  image_url              :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation
  #checks to authenticate users. as long as there is a password_digest field in the database and :password and :password_confirmation
  #then has_secure_password will encrypt, then check that pass and pass_conf match then store in pass_digest
  has_secure_password

  #every user can have many lists
  has_many :lists, :dependent => :destroy
  has_many :edit_requests

  #has many list_items
  has_many :list_items

  #has many restaurants through list_items
  has_many :restaurants, :through => :list_items

  #has many cities through lists
  has_many :cities, :through => :lists

  #every user has many relationships - also should destroy the relationship if the user is destroyed
  has_many :relationships, :foreign_key => "follower_id", :dependent => :destroy

  #can say User.followed_users => returns an array of followed users for the User and uses the relationships table followed_id as the source
  has_many :followed_users, through: :relationships, source: :followed

  #can say User.followers => returns an array of followers for the user. using the Relationship class and using reverse_relationships
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  #a user has many comments
  has_many :comments, :dependent => :destroy

  #a user has many checkins
  has_many :checkins, :dependent => :destroy

  #before you save the user to the database - downcase the email
  before_save { |user| user.email = email.downcase }
  #before the save create the remember_token for the specific user automatically
  before_save :create_remember_token

  #validates the user password for length and presence
  validates :password, :presence => true, :length => { :minimum => 4, :maximum => 50}
  validates :password_confirmation, :presence => true, :length => {:minimum => 4, :maximum => 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :first_name, length: {maximum: 50}
  validates :last_name, length: {maximum: 50}
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}

  def full_name
    "#{first_name} #{last_name}"
  end

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  #create a relationship between this user's followedid and the other user's id
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)

    #send a mail to user that is followed - This might need to be placed in a job later
    UserMailer.mail_followed_user(self, other_user).deliver
  end

  #destroy the relationship
  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  #send the password reset after generating and storing a new token
  def send_password_reset
    # generate a new token to reset password after email is asked for
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    # save the token and the password time
    save(validate: false)
    # send the mail with the token
    UserMailer.password_reset(self).deliver
  end

  # send an invite to a new user email address
  def send_invite_to_new_user(new_user_email)
    UserMailer.invite_user(self, new_user_email).deliver
  end

  #create a static method search on a query
  def self.search(query)
    if query.present?
      results = []
      queries = query.split(' ')
      queries.each do |q|
        results << find(:all, conditions: ['lower(first_name) LIKE ? OR lower(last_name) LIKE ?', "%#{q.downcase}%","%#{q.downcase}%" ])
      end
      return results.uniq.flatten
    else
      find(:all)
    end
  end

  # TODO: this is going to be slow, probably want to use a text search
  def self.text_search(query)
    if query.present?
      queries = query.split(' ').map(&:strip).select(&:present?)
      queries.map do |q|
        find(:all, conditions: ['lower(first_name) LIKE ? OR lower(last_name) LIKE ?', "%#{q.downcase}%", "%#{q.downcase}%" ])
      end.flatten.compact.uniq
    end
  end

  def avatar_url(size = 50)
    return image_url unless image_url.blank?
    gravatar_id = Digest::MD5::hexdigest(email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?r=r&size=#{size}"
  end

  def fb_post(message)
    if self.provider == 'facebook'
      begin
        me = FbGraph::User.me(self.remember_token)
        me.feed!(message: message)
      rescue
        # handle failed user post - do nothing for now
      end
    end
  end

  def list_for(restaurant)
    lists.find_or_create_by_city_id(restaurant.city_id)
  end

  # THIS IS A HACK RIGHT NOW - NEED TO FIX THIS LATER.
  # CURRENTLY USING FARM'S ACCESS TOKEN TO GET FB STUFF
  def fb_search_token
    return remember_token if fb_id
    User.find_by_email('farm.cp@gmail.com').remember_token
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.fb_id = auth['uid']
      user.remember_token = auth['credentials']['token']
      user.first_name = auth['info']['first_name']
      user.last_name = auth['info']['last_name']
      user.email = auth['info']['email']
      user.image_url = auth['info']['image']
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      UserMailer.welcome_email(user).deliver
    end
  end

  def to_s
    email
  end

  def admin?
    self.admin
  end

  private

  def create_remember_token
    if self.provider != 'facebook'
      self.remember_token = SecureRandom.urlsafe_base64
    end
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/users_controller.rb
require 'will_paginate/array'
class UsersController < ApplicationController
  #calls this before any of the other defined actions (here just :edit and :update) in this controller
  before_filter :signed_in_user, except: [:new, :create]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    params[:user][:password_confirmation] = params[:user][:password]
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "You have successfully logged in " + @user.first_name.to_s + "!"

      # TODO: this should be handled via queue
      UserMailer.welcome_email(@user).deliver

      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @lists = @user.lists
    @user_feed = Story.includes([:list, :list_item, :comment]).where(:user_id => @user.id).order('created_at desc').paginate(:page => params[:page])

    #get all restaurants around you from people you follow and your own restaurants
    @friends = @user.followed_users
    current_user_restos = current_user.restaurants

    @maps_json = (@friends.collect{|f| f.restaurants} + current_user_restos).flatten.to_gmaps4rails
    @user_image = @user.avatar_url
    #if the user is a facebook user - get a list of their friends who is on facebook and also on bitelist
    @non_followed_fb_users = []
    if @user.fb_id && @user.remember_token
      # TODO: fix this
      begin
        fb_user = FbGraph::User.me(current_user.remember_token)
        #friends that are on bitelist minus the users that you follow
        fb_user_friends = fb_user.friends.map{|u| u.raw_attributes['id']} & User.all.map{|u| u.fb_id}
        fb_followed_users = @user.followed_users.map{|u| u.fb_id}.compact.to_a
        #randomly select 3 users that are your friends from facebook that you haven't followed on bitelist
        @non_followed_fb_users = (fb_user_friends - fb_followed_users).collect!{|id| User.find_by_fb_id(id)}.shuffle.first(3)
      rescue
        # shit is breaking
      end
    end

    if current_user? @user
      feed_users = [current_user.followed_users, current_user].flatten
      @my_feed = Story.includes_all.where(:user_id => feed_users.map(&:id)).order('created_at desc').paginate(:page => params[:page])
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      #if you can update a user then handle the update for the user
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @results = User.order('first_name, last_name')
    @results_user_count = @results.count
    @results_restaurant_count = 0
    respond_to do |format|
      format.html
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User has been removed."
    redirect_to users_path
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  #return all followeds
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    if params[:q]
      @followeds = @user.followed_users.search(params[:q])
    end

    respond_to do |format|
      format.html {render 'show_follow'}
      format.json {render :json => @followeds.to_json(:only => [:id], :methods => [:full_name])}
    end

  end

  #return all followers
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    if params[:q]
      @followers = @user.followers.search(params[:q])
    end

    respond_to do |format|
      format.html {render 'show_follow'}
      format.json {render :json => @followers.to_json(:only => [:id], :methods => [:full_name])}
    end
  end

  def syncable_users
    if params[:q]
      # TODO can do this in a single query with arel magic
      friends = current_user.followers.search(params[:q]) | current_user.followed_users.search(params[:q])
      json = friends.to_json(:only => [:id], :methods => [:full_name])
    else
      json = '[]'
    end

    respond_to do |format|
      format.json { render :json => json }
    end
  end

  def fb_friends
    if current_user.provider == 'facebook'
      me = FbGraph::User.me(current_user.remember_token)
      @friends = me.friends
    else
      @friends = []
    end
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # POST method to invite by email
  def invite_by_email
    if params[:email] =~ VALID_EMAIL_REGEX
      new_user_email = params[:email]
      current_user.send_invite_to_new_user(new_user_email)
      flash[:success] = 'You have invited your friend!'
    else
      flash[:error] = 'You have entered an invalid email address'
    end

    redirect_to fb_friends_user_path
  end

  private

  def correct_user
    @user = User.find(params[:id])

    unless current_user?(@user)
      flash[:notice] = "You do not have access to this page."
      redirect_to new_session_path
    end
  end

  def user_params
    params[:user].slice(:first_name, :last_name, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_tag(user, options = {})
    size = options.delete(:size) { 50 }
    link = options.delete(:link) { false }
    link_to user do
      #data-title attribute is used for showing tooltip on restaurants/show
      image_tag(user.avatar_url, alt: user.full_name, class: 'gravatar', size: size, "data-title" => user.full_name)
    end
  end

  def active_unless_current_user
    current_user?(@user) ? '' : 'active'
  end
end

app/views/users/_follow.html.haml
= form_for(current_user.relationships.build(followed_id: @user.id), remote:true) do |f|
  %div= f.hidden_field :followed_id
  = f.submit "Follow", class: "btn btn-primary"

app/views/users/_follow_form.html.haml
- unless current_user?(@user)
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_unfollow.html.haml
= form_for(current_user.relationships.find_by_followed_id(@user), html: { method: :delete }, remote:true) do |f|
  = f.submit "Unfollow", class: "btn"

app/views/users/edit.html.haml
= provide(:title, 'Edit Profile')

%h1.big_title
  Settings
.row
  .span6.offset3
    = form_for @user do |f|
      = render 'shared/error_messages', :record => @user
      = f.label :first_name
      = f.text_field :first_name
      = f.label :last_name
      = f.text_field :last_name

      = f.label :password
      = f.password_field :password

      = f.label :password_confirmation
      = f.password_field :password_confirmation

      = f.submit "Save changes", class: "btn btn-large btn-primary"

    - if !@user.fb_id
      = avatar_tag @user
      = link_to 'change', 'http://gravatar.com/emails'

app/views/users/fb_friends.html.haml
= provide(:title, 'Invite Friends')

%h1.big_title
  Invite Friends

- # invite friends through email
.row
  .span4.offset4.center
    = form_tag invite_by_email_user_path, :method => :post do
      = label_tag "Please enter your friend's email below:"
      = text_field_tag :email, params[:email]
      = submit_tag "Send Invite!", class: 'btn btn-primary'
-#
  %ul.users
    - @friends.each do |fb_friend|
      %li
        = image_tag fb_friend.picture
        = fb_friend.name

app/views/users/github.html.haml
- provide(:title, 'Github Request')

%h1.big_title
  Request Github Access

.row
  .span4.offset4.center
    = form_tag request_github_access_user_path, :method => :post do
      = label_tag "Please enter your Github handle:"
      = text_field_tag :git_handle, params[:git_hanlde]
      = submit_tag "Request Access!", class: 'btn btn-primary'

app/views/users/index.html.haml
= provide(:title, 'Search')

%h1.big_title
  Search

- # render the followers and followeds
%section{style: 'position:absolute; left: 50%; margin-left:-65px;'}
  = render 'layouts/stats'
%br/
%br/
%br/

.tabbable
  %ul.nav.nav-tabs
    %li{:class => @results_user_count >= @results_restaurant_count ? 'active' : ''}
      %a{"data-toggle" => "tab", :href => "#tab1", style: 'font-weight:bold;'} 
        Users (
        =@results_user_count
        )
    %li{:class => @results_user_count < @results_restaurant_count ? 'active' : ''}
      %a{"data-toggle" => "tab", :href => "#tab2", style: 'font-weight:bold;'} 
        Restaurants (
        = @results_restaurant_count
        )

  .tab-content
    #tab1.tab-pane{ :class => @results_user_count >= @results_restaurant_count ? 'active' : ''}
      - @results.each do |result|
        -if result.instance_of?User
          %ul.users
            %li
              = avatar_tag result, link: true
              = link_to result.full_name, result
              - if current_user.admin? && !current_user?(result)
                = link_to "Remove", result, method: :delete, confirm: "Are you sure you want to delete #{result.full_name}?", style: 'float: right;'

    #tab2.tab-pane{ :class => @results_user_count < @results_restaurant_count ? 'active' : ''}
      - @results.each do |result|
        - if result.instance_of?Restaurant
          - if result.fb_place_id
            %ul.users
              %li
                = image_tag result.picture_url, class: "gravatar", size: "50x50"
                = link_to result.name, result
                %br/
                = result.gmaps4rails_address

app/views/users/new.html.haml
- provide(:title, 'Sign up')

%h1.big_title
  Sign Up

.row
  .span4.offset4.center
    = render 'shared/error_messages', :record => @user
    = form_for @user do |f|
      .pull-left
        = f.label :first_name
      = f.text_field :first_name
      .pull-left
        = f.label :last_name
      = f.text_field :last_name
      .pull-left
        = f.label :email
      = f.email_field :email
      .pull-left
        = f.label :password
      = f.password_field :password
      = f.submit "Create my Account", class: "btn btn-large btn-primary"

app/views/users/show.html.haml
= provide(:title, @user.full_name)

.row
  %aside.span4
    %section
      %h3{style: 'margin-bottom:5px;'}
        = image_tag @user.avatar_url, size:'50', class: 'gravatar'
        = @user.full_name
      - if current_user? @user
        = link_to new_list_path, :class => "btn btn-warning" do
          %i.icon-plus.icon-white
          Add Bitelist
      - else
        = render 'follow_form' if signed_in?
    %section.pad_bottom
      = render 'layouts/stats'

    - # if the current user is the user then show the map
    - if current_user? @user
      - #show the map
      #map-nearby
        %h3.big_title
          Bites Near You
          %ol.lists
            %li
        = gmaps("map_options" => {"detect_location" => false, "center_on_user" => true, "auto_zoom" => false, "zoom" => 12, "auto_adjust" => false, "markers" => {"data" => @maps_json}})
        %br/
        %br/
    - # only show when a user is logged in or has something in their lists
    - if @user.lists.any?
      %h3.big_title
        - if current_user? @user
          Your
        Bitelists
      %ol.lists
        %li
          = render "lists/list"
    - if  current_user? @user and @non_followed_fb_users.any? 
      %h3.big_title
        Follow other Biters
      %ol.lists
        %li
        - @non_followed_fb_users.each do |user|
          = avatar_tag(user, size:50, link:true)
          = link_to user.full_name, user
          #follow_form
            = form_for(current_user.relationships.build(followed_id: user.id), id:'follow_form') do |f|
              %div
                = f.hidden_field :followed_id
              = f.submit "Follow", class: "btn btn-primary pull-right", style: 'margin-top:-30px;'
          %br/
    .pad_bottom
      = image_tag 'divider_big_transparent.jpg'

  .span8.tabbable
    %ul.nav.nav-tabs
      - if current_user? @user
        %li.active
          %a{"data-toggle" => "tab", :href => "#tab1", style:'font-weight:bold;'} Bite Feed
      %li{ :class => active_unless_current_user }
        %a{"data-toggle" => "tab", :href => "#tab2", style:'font-weight:bold;'}
          - if current_user? @user
            My
          Activity

    .tab-content
      - if current_user? @user
        #tab1.tab-pane.active
          - if @my_feed.any?
            %ol.lists
              = render 'stories/stories', stories: @my_feed
          - else
            .well
              Nothing new has happened yet :(
      #tab2.tab-pane{ :class => current_user?(@user) ? '' : 'active' }
        - if @user_feed.any?
          %ol.lists
            = render 'stories/stories', stories: @user_feed
        - else
          .well
            Nothing new has happened yet :(
:javascript 
  $(document).ready(function(){
    $('.gravatar').tooltip();
    Gmaps.loadMaps();
  });

- content_for :scripts do
  :javascript
    Gmaps.map.geolocationSuccess = function(){
      var lng = Gmaps.map.userLocation.lng();
      var lat = Gmaps.map.userLocation.lat();
      //load map then add the markers
      $('.map_container').hide();
      $('.map_container').show();

      //add markers from controller
      Gmaps.map.addMarkers(#{@maps_json});

      var user_image = "http://wiki.alumni.net/wiki/images/thumb/5/55/Wikimap-blue-dot.png/50px-Wikimap-blue-dot.png";

      //add current location marker
      Gmaps.map.addMarkers([{
        "lng": lng,
        "lat": lat,
        "width":"40",
        "height":"48",
        "picture": user_image
      }]);

      //center the screen on your current location
      Gmaps.map.serviceObject.setCenter(new google.maps.LatLng(lat, lng));
      Gmaps.map.serviceObject.setZoom(14);
    };

app/views/users/show_follow.html.haml
= provide(:title, @title)

.row
  %aside.span4
    %section
      = avatar_tag @user
      %h1= @user.full_name
      %span= link_to "view my profile", @user

    %section
      = render 'layouts/stats'

  .span8
    %h3.big_title= @title
    %br

    %ul.users
      - @users.each do |user|
        %li
          = avatar_tag user, link: true
          = link_to user.full_name, user
    = will_paginate @users