config/routes.rb
ListApp::Application.routes.draw do
  resources :password_resets

  match "signup/", to: 'users#new'

  match 'team/', to: 'static_pages#team'
  match 'about/', to: 'static_pages#about'
  match 'home/', to: 'static_pages#home'

  match 'contribute/', to: 'static_pages#contribute'
  match 'sync/', to: 'sync#show'
  match 'get_sync/', to: 'sync#get_sync'

  match '/auth/facebook/callback', to: 'sessions#facebook'
  match '/auth/failure', to: redirect('/')
  root :to => 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
      get :fb_friends
      post :invite_by_email
    end
    collection do
      get :syncable_users
    end
  end

  resources :relationships, only: [:destroy, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :lists, :only => [:create, :destroy, :new, :show] do
    member do
      post :add_to
    end
  end
  resources :list_items, :only => [:create, :destroy]
  resources :restaurants, :only => [:new, :create, :show, :edit] do
    member do
      post :add_to_list
      post :post_to_facebook
      resources :comments, :only => [:create, :destroy]
    end
    collection do
      get :search
    end
  end

  resources :edit_requests, only: [:index, :create, :show] do
    member do
      post :accept
      post :reject
    end
  end
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete #this means it will be invoked using the DELETE request

  match '/search', to: 'search#search'

end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id           :integer         not null, primary key
#  name         :string(255)
#  picture_url  :string(255)
#  phone_number :string(255)
#  category     :string(255)
#  address      :string(255)
#  postal_code  :string(255)
#  comments     :string(255)
#  created_at   :datetime        not null
#  updated_at   :datetime        not null
#  city_id      :integer
#  active       :boolean
#  latitude     :float
#  longitude    :float
#  gmaps        :boolean
#  yelp_url     :string(255)
#  fb_place_id  :string(255)
#

class Restaurant < ActiveRecord::Base
  acts_as_gmappable

  # attr_accessible :title, :body
  #not sure we want to expose all fo these fields
  attr_accessible :name, :phone_number, :category, :address, :postal_code, :city_id, :active, :yelp_url, :picture_url, :fb_place_id, :latitude, :longitude, :website_url

  #a restaurant belongs to a single city (create new entry for each restaurant chain location)
  belongs_to :city
  has_one :list_item, :dependent => :destroy

  #a restaurant has many comments and the comments are dependent that the restaurant exists
  has_many :comments, :dependent => :destroy
  has_many :edit_requests, dependent: :destroy

  validates :name, :presence => true
  validates :phone_number, allow_blank: true, :format => {with: /\d{10}/, message: "(Only 10 digit numbers are allowed)"}, numericality: {only_integer: true}

  geocoded_by :gmaps4rails_address
  after_validation :geocode

  before_validation :fix_phone_number

  #pass in the location so that can set model lat/lng data
  def gmaps4rails_address
    "#{address}, #{city_state_zip}"
  end

  def gmaps4rails_infowindow
    "<img src=\"#{picture_url}\" width='40' height='40' style='float:left; margin-right:15px;'>
    <a href=\"/restaurants/#{id}\"><b>#{name}</b></a>
    <br/>
    #{address}
    <br/>
    #{city_state}"
  end

  def city_state_zip
    "#{city.name}, #{city.state} #{postal_code}"
  end

  def city_state
    "#{city.name}, #{city.state}"
  end

  #get rid of all non digits then validate
  def fix_phone_number
    number = phone_number.to_s.gsub(/\D/, '')
    number = number[1..-1] if number.starts_with?('1')
    self.phone_number = number
  end

  def self.in(city_id)
    where(:city_id => city_id)
  end

  # TODO: this is going to be slow, probably want to use a text search
  def self.text_search(query)
    if query.present?
      query.split(' ').map do |q|
        find(:all, conditions: ['fb_place_id IS NOT NULL AND lower(name) LIKE ?', "%#{q.downcase}%"])
      end.flatten.compact.uniq
    end
  end

  def self.search(query)
    results = [search_by_yelp(query)  ].flatten
    results = [search_by_prefix(query)].flatten if results.blank?
    results = [search_rest(query)     ].flatten if results.blank?
    results
  end

  def self.create_from_facebook(fb_id, city_id)
    fetched_result = FbGraph::Place.fetch(fb_id)
    restaurant_options = {
      :name => fetched_result.name,
      :picture_url => fetched_result.picture,
      :phone_number => fetched_result.phone,
      :category => fetched_result.category,
      :address => fetched_result.location.street,
      :postal_code => fetched_result.location.zip,
      :city_id => city_id,
      :active => true,
      :fb_place_id => fetched_result.identifier.to_s,
      :latitude => fetched_result.location.latitude,
      :longitude => fetched_result.location.longitude,
    }
    if fetched_result.website
      website = fetched_result.website.split(' ')[0]
      website = "http://#{website}" unless website.match(/^https?:\/\//)
      restaurant_options[:website_url] = website
    end
    create!(restaurant_options)
  end

  def to_s
    name
  end

  def self.search_by_yelp(query)
    where(:yelp_url => query)
  end

  def self.search_by_prefix(query)
    where(['name ilike ?', "#{query}%"])
  end

  def self.search_rest(query)
    where(['name ilike ?', "%#{query}%"])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :signed_in_user, :only => [:add_to_list]
  before_filter :require_restaurant, only: [:show, :edit, :add_to_list]

  #GET page for creating a new restaurant
  def new
    @restaurant = Restaurant.new
  end

  #need to show the restaurant details and comments
  def show
    @maps_json = @restaurant.to_gmaps4rails
    #get comments for the current restaurant - only show the followers' and followed users' comments
    if current_user
      friends_ids = current_user.followers.map(&:id) | current_user.followed_users.map(&:id) | [current_user.id]
      @comments = Comment.where(:restaurant_id => params[:id], :user_id => friends_ids.uniq).flatten

      #get followed users that have this restaurant
      @followed_users = current_user.followed_users.select{|user| user.restaurants.include?Restaurant.find(params[:id])}

      if FbGraph::User.me(current_user.remember_token).permissions.include?(:publish_checkins)
        @fb_checkin = true
        #if the current user checked in within 10 min, don't allow them to check in
        if current_user.checkins.count > 0
          if Time.now - current_user.checkins.order("created_at").last.created_at > 600
            @allow_checkin = true
          else
            @allow_checkin = false
          end
        else
          @allow_checkin = true
        end
      end
    else
      @comments = []
    end
  end

  def edit
    @edit_request = EditRequest.new
  end

  #POST action for creating a new restaurant
  def create
    @restaurant = Restaurant.new(params[:restaurant])
    city_input = City.find(params[:city][:name])
    @restaurant.city_id = city_input.id
    if @restaurant.save
      flash[:success] = "Thank you! You've successfully submitted a restaurant to Bitelist!"
      redirect_to new_restaurant_path
    else
      render 'new'
    end
  end

  #loopj hits this controller automatically and tacks on a param "q"
  #TO DO: need to add ability to search current database from places that are added internally
  def search
    # [issue #41] replace possessive apostroph-s with just s; e.g. "Bear's Ramen House"
    query = params[:q].to_s.strip.gsub(/'s\b/, "s")
    if query.present?
      current_city = City.includes(:sub_cities).find(params[:city_id])
      fb_search_options = {
        center: current_city.fb_center,
        access_token: current_user.fb_search_token
      }
      results = FbGraph::Place.search(query, fb_search_options).map do |place|
        if current_city.acceptable_fb_place?(place) && place.location.street != "" && place.location.city != ""
          {id: place.identifier, name: place.name, address: place.location.street, city: place.location.city, url: place.fetch.picture}
        end
      end.compact
    else
      results = []
    end

    render :json => results.to_json
  end

  # handle post directly from restaurant to add to list
  def add_to_list
    list = current_user.list_for(@restaurant)
    list.list_item_for(@restaurant)

    redirect_to list
  end

  #POST checkin to facebook
  def post_to_facebook
    restaurant = Restaurant.find(params[:id])

    place = FbGraph::Place.fetch(restaurant.fb_place_id)
    FbGraph::User.me(current_user.remember_token).checkin!(:coordinates => place.location, :place => place)

    #no body for now
    Checkin.create(:restaurant_id => restaurant.id, :user_id => current_user.id)

    flash[:info] = "You have checked in on Facebook!"

    redirect_to restaurant
  end

  private

  def require_restaurant
    @restaurant = Restaurant.find(params[:id]) or render status: 404
  end
end

app/views/restaurants/edit.html.haml
= provide(:title, @restaurant.name)

%h1 Edit restaurant info

= form_for @edit_request, html: {class: 'form-horizontal'} do |f|
  = f.hidden_field :restaurant_id, value: @restaurant.id
  .control-group
    = label_tag 'restaurant[name]', 'Restaurant name', class: 'control-label'
    .controls
      = text_field_tag 'restaurant[name]', @restaurant.name
  .control-group
    = label_tag 'restaurant[picture_url]', 'Picture URL', class: 'control-label'
    .controls
      = text_field_tag 'restaurant[picture_url]', @restaurant.picture_url
  .control-group
    = label_tag 'restaurant[phone_number]', 'Phone number', class: 'control-label'
    .controls
      = text_field_tag 'restaurant[phone_number]', @restaurant.phone_number
  .control-group
    = label_tag 'restaurant[category]', 'Category', class: 'control-label'
    .controls
      = text_field_tag 'restaurant[category]', @restaurant.category
  .control-group
    = label_tag 'restaurant[address]', 'Address', class: 'control-label'
    .controls
      = text_field_tag 'restaurant[address]', @restaurant.address
  .control-group
    = label_tag 'restaurant[postal_code]', 'ZIP code', class: 'control-label'
    .controls
      = text_field_tag 'restaurant[postal_code]', @restaurant.postal_code
  .control-group
    = label_tag 'restaurant[website_url]', 'Website URL', class: 'control-label'
    .controls
      = text_field_tag 'restaurant[website_url]', @restaurant.website_url

  .control-group
    .controls
      = f.submit 'Submit edit request', class: 'btn btn-primary'

app/views/restaurants/new.html.haml
%h1.big_title
  Bite Application

.row
  .span6.offset3
    .hero-unit.center
      %h1.big_title
        Come Back Soon!
-#    = render 'shared/error_messages', :record => @restaurant
-#    = form_for @restaurant do |f|
-#      = f.label :name
-#      = f.text_field :name
-#      = f.label :address
-#      = f.text_field :address
-#      = f.label :phone_number
-#      = f.text_field :phone_number
-#      = f.label :picture_url
-#      = f.text_field :picture_url
-#      = f.label :postal_code
-#      = f.text_field :postal_code
-#      = fields_for :city, @city do |u|
-#        = u.label "City"
-#        = u.select :name, options_for_select(City.select_options)

-#      = f.submit "Request Restaurant", class: "btn btn-primary"

app/views/restaurants/show.html.haml
= provide(:title, @restaurant.name)

.row
  %aside.span4
    %section
      %h1{:style => "padding-bottom: 5px; float: left;"}
        = image_tag(@restaurant.picture_url, size: '50x50', title: @restaurant.name, alt: @restaurant.name)

      %div{style: 'margin-left: 7px; float: left;'}
        %h1
          = truncate(@restaurant.name, length: 20)
          %br/
        .pull-left
          = link_to_phone(@restaurant.phone_number) if @restaurant.phone_number.present?
    .pull-left
      - # if current_user has a list in the current restaurant's city then allow them to add the current resto to that city
      - if current_user and current_user.cities.include?(@restaurant.city)
        - if current_user.restaurants.include?(@restaurant)
          %i.icon-ok
          This is in your Bitelist!
        - else
          %i.icon-plus
          = link_to "Add to your list", add_to_list_restaurant_path(@restaurant), method: 'post'
        %br/
      - else
        - if current_user
          %i.icon-plus
          = link_to "Create a #{@restaurant.city.name} Bitelist!", new_list_path
          %br/
        - else
          %i.icon-plus
          = link_to "Sign in to create a Bitelist!", signin_path
          %br/
      - if @restaurant.category
        %b Category:
        = truncate(@restaurant.category, length: 30)

      - # if the current user has checkin privilages allow them to checkin
      - if @fb_checkin and current_user.provider == "facebook" and @restaurant.fb_place_id and @allow_checkin
        %br/
        %i.icon-flag
        = link_to "Checkin with Facebook!", post_to_facebook_restaurant_path, method: "post"
      - if @restaurant.website_url
        %br/
        %b Website:
        = link_to truncate(@restaurant.name, length: 30), @restaurant.website_url, :target => '_blank'
    - if @restaurant.website_url
      %br/

    %br/
    %br/
    %br/
    %br/
    .pull-left
      = @restaurant.address
      %br/
      = @restaurant.city_state_zip
      %br/
      %i.icon-road
      = link_to "Get Directions", "javascript:get_maps('#{@restaurant.gmaps4rails_address}');"
      %br/
      - if current_user
        %i.icon-pencil
        = link_to 'Edit info', edit_restaurant_path, title: 'edit restaurant info'
    %br/
    %br/
    %br/
    %br/

    - if current_user && @followed_users.any?
      %ol.lists
        .row
          %aside.span4
            %h3.big_title Fellow Biters
            %br/
            %li
              - @followed_users.each do |user|
                = avatar_tag(user, size:50, link:true)
      %br/
      %br/
      %section

  .span8
    - # put the restaurant's website, pictures, address, comments here
    %h3.big_title Location
    %ol.lists
      %li
        = gmaps("map_options" => { "zoom" => 15, "auto_zoom" => false }, "markers" => { "data" => @maps_json })

    %br/
    - if signed_in?
      %h3.big_title
        Comments
      %div
        = render 'comments/comment'
    - else
      .well
        %h2{style:'margin-bottom: 0px;'}
          = link_to "Sign in to get exclusive content!", signin_path
:javascript
  $(document).ready(function(){
    $('.gravatar').tooltip();
  });

  function get_maps(location){
    if(/(iPhone|iPod|iPad)/i.test(navigator.userAgent)) {
      if(/OS [2-5]_\d(_\d)? like Mac OS X/i.test(navigator.userAgent)) {
        // iOS 2-5 go to google maps
        window.location = 'http://maps.google.com/maps?saddr=Current+Location&daddr=' + location;
      } else if(/CPU like Mac OS X/i.test(navigator.userAgent)) {
        // iOS 1 go to google maps
        window.location = 'http://maps.google.com/maps?saddr=Current+Location&daddr=' + location;
      } else {
        // iOS 6 or Newer go to apple maps
        window.location = 'http://maps.apple.com/maps?daddr=' + location;
      }
    } else {
      //default is to go to google maps
      window.location = 'http://maps.google.com/maps?saddr=Current+Location&daddr=' + location;
    }
  }