config/routes.rb
ListApp::Application.routes.draw do
  resources :password_resets

  match "signup/", to: 'users#new'

  match 'team/', to: 'static_pages#team'
  match 'about/', to: 'static_pages#about'
  match 'home/', to: 'static_pages#home'

  match 'contribute/', to: 'static_pages#contribute'
  match 'sync/', to: 'sync#show'
  match 'get_sync/', to: 'sync#get_sync'

  match '/auth/facebook/callback', to: 'sessions#facebook'
  match '/auth/failure', to: redirect('/')
  root :to => 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
      get :fb_friends
      post :invite_by_email
    end
    collection do
      get :syncable_users
    end
  end

  resources :relationships, only: [:destroy, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :lists, :only => [:create, :destroy, :new, :show] do
    member do
      post :add_to
    end
  end
  resources :list_items, :only => [:create, :destroy]
  resources :restaurants, :only => [:new, :create, :show, :edit] do
    member do
      post :add_to_list
      post :post_to_facebook
      resources :comments, :only => [:create, :destroy]
    end
    collection do
      get :search
    end
  end

  resources :edit_requests, only: [:index, :create, :show] do
    member do
      post :accept
      post :reject
    end
  end
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete #this means it will be invoked using the DELETE request

  match '/search', to: 'search#search'

end

app/views/layouts/_footer.html.haml
%footer.footer
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Team", team_path
      - if current_user
        %li= link_to "Restaurant owners", contribute_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %ul.nav
        = link_to image_tag('bitelist_logo.gif', :size => '108x30', style: 'margin-top:5px; margin-right:10px;'), root_path
        %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      .nav-collapse
        %nav
          - if signed_in?
            .navbar-search.pull-left
              = form_tag search_path, method:'get' do
                = text_field_tag :search, '', class: 'search-query', placeholder: 'Search for people and bites...', style: 'background-color:white; margin: 3px 0px -5px 0px; border-style:none; width: 250px;'
          %ul.nav.pull-right
            - if signed_in?
              %li
                = link_to current_user do
                  %i.icon-user.icon-white
                  Profile

              %li
                = link_to sync_path do
                  %i.icon-refresh.icon-white
                  Sync
              %li#fat-menu.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  %i.icon-folder-open.icon-white
                  Account
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to fb_friends_user_path(current_user) do
                      %i.icon-envelope
                      Invite Friends
                  %li
                    = link_to edit_user_path(current_user) do
                      %i.icon-cog
                      Settings
                  %li
                    - if current_user.admin?
                      = link_to edit_requests_path do
                        %i.icon-pencil
                        Edit requests
                        %span.label.label-important
                          = EditRequest.needs_review.count

                  %li.divider
                  %li
                    = link_to signout_path, method: "delete" do
                      %i.icon-off
                      Signout
            - else
              %li
                = link_to signin_path do
                  %i.icon-lock.icon-white
                  Signin

app/views/layouts/_lists.html.haml
- @lists.each do |list|
  .well
    %h3.pull-left= link_to list.city.name_with_state, list
    - if current_user?(list.user)
      = link_to 'x', list, method: :delete, confirm: "Are you sure you want to delete this List?", style: "font-size: 20px; font-style:bold; margin-top:-3px;", class: 'close'

app/views/layouts/_stats.html.haml
- @user ||= current_user
.stats
  = link_to following_user_path(@user) do
    %strong#following.stat
      = @user.followed_users.count
    following
  = link_to followers_user_path(@user) do
    %strong#followers.stat
      = @user.followers.count
    followers

app/views/layouts/application.html.haml
!!!

%html
  %head
    %title
      = full_title yield(:title)
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    /[if lt IE 9]
      %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}
    = stylesheet_link_tag "gmaps4rails"
    = analytics_init if Rails.env.production?
    = analytics_init local: Rails.env.development?

    = javascript_include_tag "jquery.tokeninput.js"
    = stylesheet_link_tag "token-input-facebook.css"

    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
  %body
    = render 'layouts/header'

    - flash.each do |key, value|
      .alert{ :class => "alert-#{key}" }= value

    .container
      = yield

      = render 'layouts/footer'

      = yield :scripts